### ISSUE TITLE
SQS Policy code is incorrect with typos and not functional 

### ISSUE THREAD

**Issue by chotafakir** [aws-samples/aws-marketplace-serverless-saas-integration#32]
**Describe the bug**
The create entitlement logic has SQSpolice instead of policy. 

          - CreateEntitlementLogic
          - Statement:
            - Sid: SQSPolice <- typo 
              Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt EntitlementSQSQueue.Arn
          - !Ref "AWS::NoValue"

ARN is used instead of Queuename:

SQSSendMessagePolicy requires a queueName. 

More info here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#sqs-send-message-policy

**Comment by mandusm** [comment]
Some more automated testing / checking will be implemented in early 2022.

**Comment by mandusm** [comment]
@chotafakir I made a pull request to fix the Typo fir the SID. Since this is just a SID, there's no practical blocker here and the template will not fail to deploy. 

I am unclear about your comment about the QueName. Can you please clarify? 
SQSSendMessagePolicy requires the ARN of the queue. 

The Return type of `Queue.Arn` returns the full `Arn` including the QueueName as per the example in the docs: `arn:aws:sqs:us-east-2:123456789012:mystack-myqueue-15PG5C2FC1CW8`
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-properties-sqs-queues-return-values

**Comment by sgawsmp** [comment]
Hi Mandus,

Please don't fix the typo because it will break the serverless application. Stack launch fails because the CreateEntitlementLogic doesn't work. The typo right now has disabled this logic. 

Resource: !GetAtt EntitlementSQSQueue.Arn <- This is the issue. It is providing full ARN which is not supported as SQS policy resource, Only Queue names are supported. 

Thanks,

Sumeet
